### ISSUE TITLE
Add templates to issues

### ISSUE THREAD

**Issue by paulf81** [NREL/flasc#16]
The issues are missing the helpful templates that exist on the FLORIS repo, this issue is just to mark we should add them

**Comment by bayc** [comment]
I've added updated templates for issues, PRs, bugs, documentation fixes, and feature requests, leveraging the setup in the OpenFAST repo from @rafmudaf . To test/see the changes, they needed to happen in the default branch, so instead of changing the default to develop, I pushed directly to the main branch, and then merged the changes back into develop.
